### ISSUE TITLE
Feature request: exclude specific bag files in the scanroot

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics-nodes#11]
There should be a way to exclude specific bag files in the bagroot from being added to marv robotics.

We have talked about this before and there are many ways, how this could be configured, of which two examples are: 1) a ignore file similar to .gitignore or .dockerignore and 2) a marker file for while folders / sub paths similar to CATKIN_IGNORE.

I'm just mentioning this again here as an issue, because while testing marv robotics with our share of bagfiles, I noticed that marv robotics adds all our duplicate bag files that we keep in an `.original` folder (the originally recorded data even if the bag file hast undergone message migration or similar alterations. For bagbunker it a matter of just not creating a `.md5` file for the bags in the `.original` folder to ensure that they we not included.

**Comment by chaoflow** [comment]
presence of .marvignore should already lead to a subtree being ignored. Putting into docs. please reopen if broken. thx!

**Comment by NikolausDemmel** [comment]
Seems to work in 2.0.0b1
