### ISSUE TITLE
Usability: Tagging

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics-nodes#4]
Just a few remarks on my first experience with tagging. These are only very minor issues.
- [ ] It was not directly obvious to me why typing a tag in the box and clicking "save tags" did not add a tag. Now that I know you have to click "create tag ..." or press enter and have a chance to adding/removing multiple tags at once before saving the UI does make sense to me.
- [ ] clicking "tag" and then hitting "enter" adds an "empty string" tag. Not sure if you want to allow that. I is not visible in the list of tags (probably a grey box with 0px width).

**Comment by chaoflow** [comment]
partly duplicate: https://github.com/ternaris/marv/issues/3

**Comment by chaoflow** [comment]
This has been improved. Thank you for the feedback.
