### ISSUE TITLE
Only a blank page in Bosch Windows browser

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics-nodes#6]
From my Linux machine my test-site of marv robotics works fine, but from my Bosch Windows machine I only see a blank page (in both Firefox and IE). When opening the JS Console in Firefox, I see the following:

```
TypeError: arguments is not iterable
G()
 main-built.js:7614
create()
 main-built.js:7617
<anonym>
 main-built.js:6763
require()
 main-built.js:6763
<anonym>
 main-built.js:7627
 main-built.js:7614:928
```

**Comment by chaoflow** [comment]
@NikolausDemmel Which versions of Firefox and IE are that?

**Comment by NikolausDemmel** [comment]
Firefox ESR, version45.4.0, Updatekanal Bosch. 

IE: 11.0.9600.18449; Update Versions: 11.0.35.

Not sure what modifications or plugins that the Bosch setup includes might interfere here.

**Comment by NikolausDemmel** [comment]
P.S.: I just tried on Firefox in Safe Mode and that makes no difference. I get the same error and a blank page.

**Comment by NikolausDemmel** [comment]
The demo site https://ternaris.com/marv-robotics/demo seems to work fine in Bosch Firefox, but is still blank in IE (but who cares about IE... :-P).

**Comment by NikolausDemmel** [comment]
My own installation of 2.0.0b1 also works fine with FF (45.4.0), but it is still blank in IE.

It would probably be good to have short message that is shown for older, not yet supported browsers, informing about the need to use a newer browser.

**Comment by chaoflow** [comment]
We added a messages with 2.0.0b2

**Comment by NikolausDemmel** [comment]
Thanks. The error message shows up fine.
