### ISSUE TITLE
Bag download link does not work

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics-nodes#8]
When I try to download a bag file, I get the following page:

> Not Found
> 
> The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

The server log shows: 

```
[pid: 1|app: 0|req: 15/17] 10.44.53.229 (zenoway) {44 vars in 931 bytes} [Tue Oct  4 13:02:45 2016] GET /marv/api/2/fileset-details/858b00cf-0439-4acf-85bd-cb45b5730c30/download/0 => generated 233 bytes in 38 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on coe 0)
```

**Comment by chaoflow** [comment]
@NikolausDemmel we cannot reproduce with 2.0.0b1, can you?

**Comment by NikolausDemmel** [comment]
works for me as well in beta, thanks
